COMPONENT  =BlinkToRadioAppC
CFLAGS += -I$(TOSDIR)/lib/printf
CFLAGS += -DNEW_PRINTF_SEMANTICS
CFLAGS += -I$(TOSDIR)/lib/net/Deluge/BlockStorageManager
PFLAGS = -DCC2420_DEF_CHANNEL=9
include $(MAKERULES)